const mentor =[
    {
        mentor_name:"Akash1",
        mentor_id:1,
        joining_date:"21-02-21",
        subjects:[],
        student:[{}]
    },
{
    mentor_name:"Adi",
    mentor_id:2,
    joining_date:"21-02-21",
    subjects:[],
    student:[{}]
},
{
    mentor_name:"Amar",
    mentor_id:3,
    joining_date:"21-02-21",
    subjects:[],
    student:[{}]
},
{
    mentor_name:"Akbar4",
    mentor_id:4,
    joining_date:"21-02-21",
    subjects:[],
    student:[{}]
},

]

const students = [
    {
        student_name:"Sarvesh",
        student_id:1,
        joining_date:"21-02-21",
        mentor_id:1
    },
{
    student_name:"Suresh",
    student_id:2,
    joining_date:"21-02-21",
    mentor_id:1
},
{
    student_name:"Surappa",
    student_id:3,
    joining_date:"21-02-21",
    mentor_id:1
},
{
    student_name:"Sura",
    student_id:4,
    joining_date:"21-02-21",
    mentor_id:1
},
]